config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :payments, only: [:create]
    end
  end

  get '/login' => 'user_sessions#new'
  post '/login' => 'user_sessions#create'
  delete '/logout' => 'user_sessions#destroy'

  resources :merchants
  resources :transactions, only: [:index]

  root 'merchants#index'
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorize_transaction.rb
class AuthorizeTransaction < Transaction
  has_one :charge_transaction, class_name: 'ChargeTransaction', foreign_key: :ref_id
  has_one :reversal_transaction, class_name: 'ReversalTransaction', foreign_key: :ref_id

  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/charge_transaction.rb
class ChargeTransaction < Transaction
  include WithRefTransactions

  has_one :refund_transaction, class_name: 'RefundTransaction', foreign_key: :ref_id
  belongs_to :authorize_transaction, class_name: 'AuthorizeTransaction', foreign_key: :ref_id

  validates :amount, presence: true, numericality: { greater_than: 0 }

  after_commit :increase_merchant_sum, on: :create

  private

  def increase_merchant_sum
    merchant.with_lock do
      current = merchant.total_transaction_sum || 0
      merchant.total_transaction_sum = current + amount
      merchant.save!
    end
  end
end

app/models/concerns/with_ref_transactions.rb
module WithRefTransactions
  extend ActiveSupport::Concern

  included do
    before_create :verify_referenced_transaction
  end

  class_methods do
    def referenced_transaction_association
      reflect_on_all_associations(:belongs_to)
        .detect { |assoc| assoc.foreign_key == :ref_id }&.name
    end
  end

  def ref
    @ref ||= begin
      name = self.class.referenced_transaction_association
      name.present? ? public_send(name.to_sym) : nil
    end
  end

  def verify_referenced_transaction
    return if ref.blank?
    return if ref.approved? || ref.refunded?

    self.status = :error
  end
end

app/models/merchant.rb
class Merchant < User
  has_many :transactions
  has_many :applications, class_name: 'MerchantApplication', foreign_key: :merchant_id

  after_commit :create_application, on: :create

  private

  def create_application
    applications.create
  end
end

app/models/merchant_application.rb
class MerchantApplication < ApplicationRecord
  belongs_to :merchant

  before_create :generate_private_token

  private

  def generate_private_token
    self.private_token = SecureRandom.hex(16)
  end
end

app/models/refund_transaction.rb
class RefundTransaction < Transaction
  belongs_to :charge_transaction, class_name: 'ChargeTransaction', foreign_key: :ref_id

  validates :amount, presence: true, numericality: { greater_than: 0 }

  before_create :refund_charge_transaction
  after_commit :decrease_merchant_sum, only: [:create]

  private

  def decrease_merchant_sum
    merchant.with_lock do
      current = merchant.total_transaction_sum || 0
      merchant.total_transaction_sum = current - amount
      merchant.save!
    end
  end

  def refund_charge_transaction
    charge_transaction.refunded!
  end
end

app/models/reversal_transaction.rb
class ReversalTransaction < Transaction
  belongs_to :authorize_transaction, class_name: 'AuthorizeTransaction', foreign_key: :ref_id

  after_create :reverse_authorize_transaction

  private

  def reverse_authorize_transaction
    authorize_transaction.reversed!
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  enum status: %i[approved reversed refunded error]

  belongs_to :merchant

  validates :customer_email, :merchant, :status, presence: true

  scope :older_than, ->(time) { where("created_at < ?", time) }
end

app/models/user.rb
class User < ApplicationRecord
  enum status: %i[active inactive]
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :status, presence: true
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ActionController::API
      include ActionController::HttpAuthentication::Token::ControllerMethods

      before_action :authenticate_client

      protected

      def request_http_token_authentication(_realm, _message)
        render json: { data: nil, errors: { client: ['Invalid authentication credentials'] } }, status: 401
      end

      def invalid_merchant_response
        render json: { data: nil, errors: { client: ['Merchant account is inactive'] } }, status: 403
      end

      private

      def current_app
        @current_app ||= MerchantApplication.find_by(id: params[:client_id])
      end

      def current_merchant
        @current_merchant ||= current_app&.merchant
      end

      def client_inactive?
        current_merchant.present? && current_merchant.inactive?
      end

      def authenticate_client
        authenticate_or_request_with_http_token do |token, _options|
          invalid_merchant_response if client_inactive?

          client_token = current_app&.private_token
          ActiveSupport::SecurityUtils.secure_compare(token, client_token.to_s)
        end
      end
    end
  end
end

app/controllers/api/v1/payments_controller.rb
module Api
  module V1
    class PaymentsController < ApiController
      def create
        form = ::PaymentTransactionForm.new(payment_params.to_h.merge(merchant: current_merchant))

        if form.save
          render json: ChargeTransactionSerializer.new(form.charge_transaction)
        else
          render json: { errors: @form.errors.messages }
        end
      end

      private

      def payment_params
        params.permit(:amount, :customer_email, :customer_phone)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authorize_admin!
    return if current_user.is_a?(Admin)

    redirect_to login_path, alert: 'You do not have permissions to visit that page'
  end
end

app/controllers/merchants_controller.rb
# frozen_string_literal: true

class MerchantsController < ApplicationController
  before_action :authorize_admin!
  before_action :load_merchant, only: %i[destroy edit update]

  def index
    @merchants = Merchant.order(id: :desc)
  end

  def edit; end

  def update
    if @merchant.update(update_params)
      redirect_to merchants_path, notice: 'Merchant has been updated'
    else
      render :edit
    end
  end

  def destroy
    if Merchants::DestroyService.new.call(@merchant)
      redirect_to merchants_path, notice: 'Merchant has been deleted'
    else
      redirect_to merchants_path, alert: 'Unable to delete merchant with transactions'
    end
  end

  private

  def update_params
    params.require(:merchant).permit(:name, :description, :password, :password_confirmation)
  end

  def load_merchant
    @merchant = Merchant.find(params[:id])
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :authorize_admin!

  def index
    records = Transaction.all.order(id: :desc)
    @transactions = TransactionDecorator.decorate_collection(records)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  # rubocop:disable Metrics/AbcSize
  def create
    user = User.find_by(email: login_params[:email].downcase)

    if user&.authenticate(login_params[:password])
      session[:user_id] = user.id.to_s
      redirect_to root_path, notice: 'Successfully logged in!'
    else
      flash.now.alert = "Incorrect email or password, try again."
      render :new
    end
  end
  # rubocop:enable Metrics/AbcSize

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: "Logged out!"
  end

  private

  def login_params
    params.require(:login).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta(name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no")
    title
      | Payment System Task
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
  body.text-center
    .cover-container.d-flex.h-100.p-3.mx-auto.flex-column
      = render 'shared/header'
      = render 'shared/notifications'

      main.inner.cover(role="main")
        = yield

      footer.mastfoot.mt-auto

app/views/merchants/edit.html.slim
.row
  .cols-12
    h1 Edit merchant form

.row
  .cols-12
    - if @merchant.errors.present?
      .alert.alert-danger
        h4 Validation error 
        p = @merchant.errors.full_messages.join('\n')

    = form_for @merchant do |f|
      .form-group
        = f.label "Name"
        = f.text_field :name, class: "form-control"

      .form-group
        = f.label "Description"
        = f.text_field :description, class: "form-control"

      .form-group
        = f.label "Password"
        = f.password_field :password, class: "form-control"

      .form-group
        = f.label "Password confirmation"
        = f.password_field :password_confirmation, class: "form-control"

      = f.submit "Save", class: "btn btn-primary"

app/views/merchants/index.html.slim
.row
  .cols-12
    h1 Merchants

.row
  .cols-12
    table.table
      thead
        tr
          th(scope="col") ID
          th(scope="col") Email
          th(scope="col") Name
          th(scope="col") Status
          th(scope="col") Sum of transactions
          th(scope="col")
      tbody
        - @merchants.each do |merchant|
          tr
            th(scope="row")
              = merchant.id
            td = merchant.email
            td = merchant.name
            td = merchant.status
            td = merchant.total_transaction_sum || 0
            td
              = link_to 'Edit', edit_merchant_path(merchant.id)
              = link_to 'Delete', merchant_path(merchant.id), method: :delete

app/views/shared/_header.html.slim
header.masthead.mb-auto
  .inner
    nav.nav.nav-masthead.justify-content-center
      = link_to 'Merchants', merchants_path, class: "nav-link"
      = link_to 'Transactions', transactions_path, class: "nav-link"

      - if current_user.present?
        = link_to current_user.email, "", class: "nav-link active"
        = link_to 'Logout', logout_path, class: "nav-link", method: :delete
      - else
        = link_to 'Login', login_path, class: 'nav-link'

app/views/shared/_notifications.html.slim
- if notice.present?
  .alert.alert-primary(role="alert")
    = notice
- if alert.present?
  .alert.alert-danger(role="alert")
    = alert

app/views/transactions/index.html.slim
.row
  .cols-12
    h1 Transactions

.row
  .cols-12
    table.table
      thead
        tr
          th(scope="col") ID
          th(scope="col") Type
          th(scope="col") Customer Email
          th(scope="col") Status
          th(scope="col") Customer Phone
          th(scope="col") Amount
          th(scope="col")
      tbody
        - @transactions.each do |transaction|
            tr
              th(scope="row") = transaction.id
              td = transaction.type
              td = transaction.customer_email
              td = transaction.status
              td = transaction.customer_phone
              td = transaction.amount

app/views/user_sessions/new.html.slim
h1 Login

.text-left
  = form_for :login do |f|
    .form-group
      = f.label "Email"
      = f.text_field :email, autofocus: true, class: "form-control"

    .form-group
      = f.label "Password"
      = f.password_field :password, class: "form-control"

    = f.submit "Log In", class: "btn btn-primary"